[build]
target = ["x86_64-unknown-linux-gnu"]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"


[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"


# Builds statically compiled binaries
# [target.x86_64-unknown-linux-musl]
# linker = "./scripts/zig/x86_64-musl.sh"

# [target.aarch64-unknown-linux-musl]
# linker = "./scripts/zig/aarch64-musl.sh"

# To build final executable
# cargo test --no-run -Zbuild-std=std --target mips-unknown-linux-gnu
[target.mips-unknown-linux-gnu]
linker = "./scripts/toolchain/host/bin/mips-buildroot-linux-gnu-gcc"
rustflags = ["-C", "opt-level=1"]
